spring:
  application:
    name: "spring-hibernate-boot-course"
#  main:
#    lazy-initialization: true

# Turn off spring boot banner
  main:
    banner-mode: off

# datasource details
  datasource:
    url: jdbc:mysql://localhost:3306/student_tracker
    username: root
    password: root

# Configure JPA/Hibernate to auto drop and then create the table, should not be using in prod env
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 8585
#  servlet:
#    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
    health:
      show-details: always
    path-mapping:
      health: /health
  info:
    env:
      enabled: true
info:
  app:
    name: "Spring Hibernate boot Course"
    description: "Learning spring and hibernate"
    version: "1.0.0"
  project: "Personal project"


logging:
  level:
#    org.springframework.boot.actuate.endpoint: DEBUG
    # Reduce logging level, set logging level to warn
    root: warn

    # add logging configs to display SQL statements and values as well with the help of jdbc bind
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

# Custom properties here
coach:
  name: "Mickey Mouse"
team:
  name: The Disney Club
