spring:
  application:
    name: "spring-hibernate-boot-course"

server:
  port: 8585

management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
    health:
      show-details: always
    path-mapping:
      health: /health
  info:
    env:
      enabled: true
info:
  app:
    name: "Spring Hibernate boot Course"
    description: "Learning spring and hibernate"
    version: "1.0.0"
  project: "Personal project"


#logging:
#  level:
#    org.springframework.boot.actuate.endpoint: DEBUG


# Custom properties here
coach:
  name: "Mickey Mouse"
team:
  name: The Disney Club
